name: main-ci
run-name: Running Main CI by ${{ github.actor }}
on: [push]
  #pull_request:
  #  branches:
  #    - main

jobs:
  create-virtualenv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirements_files: requirements.txt

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f setup.py ]; then pip install setuptools && python setup.py install; fi
        if: steps.cache-primes.outputs.cache-hit != 'true'
  
  run-tests:
    needs: create-virtualenv
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - name: Run PyTest
        run: pytest

  check-linting:
    needs: create-virtualenv
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - name: Run PyLint
        run: pylint $(git ls-files '*.py')

  check-coding-style:
    needs: create_virtualenv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"

  check-security-vulnerability:
    needs: create-virtualenv
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - name: Run Security Vulnerability with Bandit
        run: bandit -r .


