name: pip-cache
run-name: Test Pip Cache by ${{ github.actor }}.
on: [push]

jobs:
  build-pip-cache:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
          python-version-file: '.python-version'

      - uses: actions/cache@v3
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/*requirements.txt') }} # (1)

      - name: Install dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate

          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip-sync requirements.txt; fi
          if [ -f setup.py ]; then pip install setuptools && python setup.py install; fi
